

try{
    console.log(x);
}
catch(error){
    console.error(error);
}
finally{
    console.log("This always executes");
}


console.log("You have reached the end!");